version: 2
jobs:
  build:
    working_directory: ~/Cake.CoreCLR.Runner
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet run --project Cake.CoreCLR.Runner.csproj --target "Default" --configuration "Release"
