version: 2
jobs:
  build:
    working_directory: ~/Cake.CoreCLR.Runner
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      CAKE_VERSION: 0.23.0
    steps:
      - checkout
      - run: chmod +x build.sh
      - run: ./build.sh
